controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_homepage:
    path: /
    controller: App\Controller\ArticleController::homepage

app_article_show:
    path: /articles/{slug}
    controller: App\Controller\ArticleController::show

app_article_like:
    path: /articles/{id<\d+>}/like/{type<like|dislike>}
    controller: App\Controller\ArticleLikeController::like
    methods: POST
